platform :ios, '8.3'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMSCropView_Example' do
  pod 'MMSCropView', :path => '../'
end

target 'MMSCropView_Tests' do
  pod 'MMSCropView', :path => '../'

  pod 'FBSnapshotTestCase'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
