source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMSCropView_Example' do
  pod 'MMSCropView', :path => '../'
end

target 'MMSCropView_Tests' do
  pod 'MMSCropView', :path => '../'

  pod 'FBSnapshotTestCase'
end
