source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMSCropView_Example', :exclusive => true do
  pod 'MMSCropView', :path => '../'
end

target 'MMSCropView_Tests', :exclusive => true do
  pod 'MMSCropView', :path => '../'

  pod 'FBSnapshotTestCase'
end
